apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: alpine:latest
    name: test-container1
    command:
        - sleep
        - "3600"
    volumeMounts:
      - mountPath: /dir1
        name: volumedir
  - image: alpine:latest
    name: test-container2
    command:
        - sleep
        - "3600"
    volumeMounts:
      - mountPath: /dir2
        name: volumedir
  volumes:
    - name: volumedir
      emptyDir: {}
